name: Build and deploy

on: [push, pull_request]

jobs:
  build:
    environment:
      name: testing
    env:
      HOST: ${{secrets.HOST}}
      PORT: ${{secrets.PORT}}
      DATABASE: ${{secrets.DATABASE}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      JWT_ENCODE_KEY: ${{secrets.JWT_ENCODE_KEY}}
      JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: pull git repository
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    environment: production
    steps:
      - name: pull git repository
        uses: actions/checkout@v3
      - name: Heroku deployment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
