name: Release

# run on every commit tag like "v_._._" (e.g v2.1.5)
on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: [ "Build and deploy" ]
    branches: [ main ]
    types:
      - completed

# Create GitHub Release with specified details from last commits
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: generate new release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            LICENSE
